---
- name: Install and configure Nginx
  hosts: web
  become: yes  # Use privilege escalation to run tasks as root
  vars:
    static_files_path: "/opt/nginx/static"
  tasks:
    - name: Add the Nginx APT key
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Ensure the nginx.list file exists
      file:
        path: /etc/apt/sources.list.d/nginx.list
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Add the Nginx APT repository to nginx.list
      lineinfile:
        path: /etc/apt/sources.list.d/nginx.list
        line: "deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx"
        state: present
        create: yes

    - name: Update the APT cache
      apt:
        update_cache: yes
    - name: Install the specified version of Nginx
      apt:
        name: "nginx={{ nginx_version }}"
        state: present
        update_cache: yes

    - name: Ensure the static files directory exists
      file:
        path: "{{ static_files_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy static files from control node to target
      copy:
        src: "./static/"
        dest: "{{ static_files_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Replace "/var/www/html;" with "/opt/nginx/static;"
      replace:
        path: /etc/nginx/sites-available/default
        regexp: "^\\s*root\\s+/var/www/html;"
        replace: "        root {{ static_files_path }};"

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded
