- name: Copy and run custom facts
  gather_facts: no
  hosts: nodes
  tasks:
    - name: Create directory for ansible custom facts
      become: true
      ansible.builtin.file:
        state: directory
        recurse: true  
        path: /etc/ansible/facts.d

    - name: Install custom fact file
      become: true
      ansible.builtin.copy:
        src: ./custom_facts/
        dest: /etc/ansible/facts.d

    - name: Re-read facts after adding custom fact
      ansible.builtin.setup:
        filter: ansible_local