web:
  hosts:
    web01.prod.example.com:
    web02.prod.example.com:
db:
  hosts:
    db01.prod.example.com:
      vars:
        db_version: 1400
    backup01.prod.example.com:
      vars:
        x: 5
backup:
  hosts:
    backup01.prod.example.com:
      vars:
        x: 9


